### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by Ahmadzdddd** [Bevigil/BeVigil-OSINT-CLI#2]
bevigil-cli init --api-key VVblablablablaCq

Am getting invalid API KEY

**Comment by xscorp** [comment]
This appears to be an invalid API key. Please get a valid API key at bevigil.com

**Comment by Ahmadzdddd** [comment]
I got it from the website but i didn't put mine here...!

**Comment by xscorp** [comment]
That must be a demo/placeholder API key. Please replace it with a valid one.

**Comment by Ahmadzdddd** [comment]
![image](https://github.com/Bevigil/BeVigil-OSINT-CLI/assets/142327125/8cf1c43d-90f9-4bef-8c78-b78a447a244d)

**Comment by xscorp** [comment]
Yes, please use this valid API key instead of a valid one. 
Now that issue is sorted, please delete the screenshot to avoid public misuse of it.

**Comment by Ahmadzdddd** [comment]
I get similar api key yesterday but get invalid api key while using the tool. I will check later again this key and keep you updated.

**Comment by Ahmadzdddd** [comment]
Hey again,
It's not working even using the key i showed u previously. ![image](https://github.com/Bevigil/BeVigil-OSINT-CLI/assets/142327125/6154f24d-66f1-4ac5-8e4a-abb2460dc067)

**Comment by xscorp** [comment]
Hey @Ahmadzdddd , It appears to be a legit issue with our microservice. Our team is currently looking at the issue. We will notify you in this thread as soon as the issue gets resolved. 

And thank you so much for bringing this issue up!

**Comment by xscorp** [comment]
Hey @Ahmadzdddd , The issue has been fixed. Your API key should be working now. In case it doesn't, please generate a new one and it will work. In case any more issues are encountered, please let us know.
And again, Thank you for bringing up this issue.

**Comment by Ahmadzdddd** [comment]
Its working without any sufficient credits. I would ask for private credits due to my contribution;p Enjoy and have a good yesr
